import type {
  NavBarLink,
  SocialLink,
  Identity,
  AboutPageContent,
  ProjectPageContent,
  BlogPageContent,
  HomePageContent,
} from "./types/config";

export const identity: Identity = {
  name: "Ruthwik Arepelly",
  logo: "/profile.jpg",
  email: "ruthwikarepelly2@gmail.com",
};

export const navBarLinks: NavBarLink[] = [
  { title: "Home", url: "/" },
  { title: "Projects", url: "/#projects" },
  { title: "About", url: "/#about" },
  { title: "Blog", url: "https://medium.com/@rello4585", external: true },
  { title: "Resume", url: "https://drive.google.com/file/d/your-resume-id/view", external: true },
];

export const socialLinks: SocialLink[] = [
  { title: "GitHub", url: "https://github.com/Ruthwik-Data", icon: "mdi:github", external: true },
  { title: "LinkedIn", url: "https://linkedin.com/in/ruthwik-arepelly", icon: "mdi:linkedin", external: true },
  { title: "Medium", url: "https://medium.com/@rello4585", icon: "mdi:medium", external: true },
];

// Home (/)
export const homePageContent: HomePageContent = {
  seo: {
    title: "Ruthwik Arepelly | AI Product Manager",
    description: "AI Product Manager focused on 0→1 evaluation-driven AI products in B2B SaaS and fintech.",
    image: identity.logo,
  },
  heroHeading: "Building 0→1 AI Products",
  heroBioFirstLine: "I'm an AI Product Manager focused on building early-stage AI products.",
  heroBioSecondLine: "I focus on shipping reliable, evaluation-first AI applications—including RAG systems, agents, and decision-support tools—where observability and unit economics are first-class constraints.",
  heroProofPoints: [
    "Built evaluation-driven LLM systems for real-world workflows",
    "Designed GPT-4o Vision pipelines for document and receipt extraction",
    "Building AI products, prototypes, and experiments in public",
  ],
  socialLinks: socialLinks,
  strategyPieces: [
    {
      title: "Tap & Pray Is Not a Payment Strategy",
      subtitle: "Why frictionless payments require strong unit economics and retention loops.",
      url: "https://medium.com/@rello4585",
      description: "A deep dive into why frictionless payments require more than just a 'tap'—they require a robust unit-economic strategy.",
      problem: "Payment roadmaps often prioritize feature-parity over strategic differentiation and unit margins.",
      mentalModel: "Payments as a strategic lever for customer retention and margin optimization, not just plumbing.",
      decisions: "Focused on 'friction vs. security' trade-offs and vendor lock-in risks.",
      successMetric: "LTV/CAC improvements through payment-driven retention loops.",
    },
    {
      title: "From Venue to Platform: The Bernabéu as a Product",
      subtitle: "Why infrastructure should be treated as a multi-tenant revenue platform.",
      url: "https://medium.com/@rello4585",
      description: "Analyzing infrastructure as a product platform that enables multi-tenant revenue streams.",
      problem: "Static physical assets failing to adapt to digital-first revenue opportunities.",
      mentalModel: "Asset-as-a-Platform: Enabling developers and partners to build 'on top' of physical space.",
      decisions: "Architecture over aesthetics; prioritizing APIs and data-capture points.",
      successMetric: "Non-matchday revenue growth and partner ecosystem health.",
    },
  ],
  links: [
    { title: "View My Work", url: "/#projects" },
    { title: "My Product Philosophy", url: "/#about" },
  ],
};

// About (/about)
export const aboutPageContent: AboutPageContent = {
  seo: {
    title: "About | Ruthwik Arepelly",
    description: "AI Product Manager focused on building 0→1 products by bridging the gap between LLM hype and production reliability.",
    image: identity.logo,
  },
  subtitle: "AI Product Manager — B2B SaaS, Fintech, Evaluation-Driven Systems",
  about: {
    bioFirstLine: "I'm an AI Product Manager focused on building early-stage AI products.",
    bioSecondLine: "My work centers on designing evaluation-driven AI applications — including RAG systems, agents, and decision-support tools — with a strong focus on reliability and practical product design.",
    image_l: { url: "/profile.jpg", alt: "Ruthwik Arepelly" },
    image_r: { url: "/profile.jpg", alt: "Ruthwik Arepelly" },
  },
  work: {
    description: `I build products that bridge the gap between complex AI and real-world value.`,
    items: [
      {
        title: "AI Product Manager",
        company: "Stealth AI",
        date: "2024 — Present",
        icon: "mdi:robot-outline",
        description: [
          "Led product development for AI-powered systems and internal tooling",
          "Designed evaluation-driven workflows for LLM features",
          "Defined product metrics around reliability, latency, and cost efficiency",
          "Collaborated with engineering teams to ship AI capabilities into production",
        ],
      },
      {
        title: "Product Manager",
        company: "Digital Connect",
        date: "2018 — 2023",
        icon: "mdi:finance",
        description: [
          "Managed product roadmap for fintech platform services",
          "Led cross-functional collaboration across engineering, design, and operations",
          "Implemented data-driven prioritization and experimentation",
          "Delivered improvements in usability and product adoption",
        ],
      },
      {
        title: "Co-Founder & Head of Product",
        company: "Photon Edu Fintech",
        date: "2016 — 2018",
        icon: "mdi:school-outline",
        description: [
          "Co-founded and built an education-focused fintech platform",
          "Led product design, roadmap, and go-to-market strategy",
          "Built MVP and scaled early product adoption",
        ],
      },
    ],
  },
  connect: {
    description: `I'm always open to discussing RAG architecture, agentic workflows, or AI product strategy.`,
    links: socialLinks,
  },
};

// Projects (/projects)
export const projectsPageContent: ProjectPageContent = {
  seo: {
    title: "Projects | Ruthwik Arepelly",
    description: "Detailed product briefs for AI, Fintech, and B2B SaaS systems.",
    image: identity.logo,
  },
  subtitle: "Product Briefs: 0→1 AI Systems",
  projects: [
    {
      id: "receiptiq",
      title: "ReceiptIQ",
      status: "Live",
      category: "Shipped Product",
      shortProblem: "Extracting data from messy, crumpled receipts is manual and error-prone.",
      shortSolution: "A vision-to-LLM pipeline that transforms receipt images into structured transaction data.",
      outcome: "Validated 18 structured transactions and 172 item-level records from 20 receipts.",
      metric: "172 item-level records extracted",
      githubUrl: "https://github.com/Ruthwik-Data",
      liveUrl: "https://receiptiq-topaz.vercel.app/",
      image: "/receiptiq_viz.png",
      galleryUrls: ["/receiptiq_viz.png", "/receiptiq.webp"],
      overview: [
        "Structured 18 transactions from 20 processed receipts",
        "Extracted 172 item-level records into a usable data model",
        "Standardized 6 merchants and generated 7 spending categories for analysis",
      ],
      problem: "Extracting data from messy, crumpled receipts is manual and error-prone. Users need a faster way to digitize receipts without typing line items.",
      whyThisMatters: "Manual receipt entry is a significant bottleneck for accountants and SMEs. Automating this eliminates hours of manual transcription and reduces costly accounting errors.",
      usersAndJobs: "Accountants, operators, and small business owners who need to capture expenses quickly and turn receipts into structured records.",
      solution: "A vision-to-LLM pipeline that transforms receipt images into structured transaction data for downstream analytics.",
      architectureContent: "Input Image → GPT-4o Vision API → JSON Structuring → Schema Validation → Analytics DB",
      techStack: ["React", "Node.js", "GPT-4o Vision", "PostgreSQL"],
      resultsAndMetrics: "The pipeline processed 20 receipts, resulting in 18 structured transactions and 172 item-level records. Standardized 6 merchants and identified 7 spending categories. One SPAR transaction was flagged as a 5.4x outlier, with Walmart representing 45.8% of total spend (Avg value: $63.17).",
      keyTakeaways: [
        "Transforms messy, crumpled receipts into high-precision structured data",
        "End-to-end Vision-to-JSON pipeline with automated schema validation",
        "Validated 172 item-level records with outlier detection for finance analytics",
      ],
      myRole: "Product Manager",
      roleBullets: [
        "Defined project scope and mapped user jobs to be done for digitizing receipts",
        "Researched and tested vision prompt logic for high-accuracy item extraction",
        "Designed system flow from image input to analytics DB",
        "Collaborated with development to validate data patterns and outlier logic",
      ],
      futureImprovements: "Implement an agentic categorization loop based on prior accounting behavior and user-specific merchant rules.",
      evaluation: {
        datasetSize: "20 receipts",
        method: "Before/after structured processing review plus manual validation.",
        primaryMetric: "Structured transactions, extracted items, merchant normalization, and category generation.",
        status: "Validated and ready to show in portfolio.",
      },
    },
    {
      id: "pennypal",
      title: "PennyPal",
      status: "Live",
      category: "Shipped Product",
      shortProblem: "Traditional financial apps lack conversational and intuitive interactions.",
      shortSolution: "A voice-first GenAI companion that answers financial queries naturally.",
      outcome: "A voice-first companion that lets users ask financial questions and receive plain-language responses.",
      githubUrl: "https://github.com/Ruthwik-Data/pennypal",
      image: "/sugarshield_diagram.png",
      galleryUrls: ["/sugarshield_diagram.png"],
      overview: [
        "Launched a voice-native financial query system.",
        "Designed intent taxonomy for personal finance queries.",
      ],
      problem: "Users are overwhelmed by complex banking UI when they just want to know their spending habits.",
      whyThisMatters: "Most banking apps are data-dense and hard to navigate. PennyPal offers a conversational layer that makes financial health as simple as asking a key question.",
      usersAndJobs: "Everyday consumers trying to quickly understand their financial health on the go.",
      solution: "A voice-first GenAI companion that answers financial queries naturally and suggests budgeting tips.",
      architectureContent: "Voice Input → Whisper API → LLM Intent Engine → Data Retrieval → TTS Output",
      techStack: ["Next.js", "OpenAI Whisper", "LLMs"],
      resultsAndMetrics: "The prototype demonstrates reliable intent classification for common financial queries in a conversational interface.",
      keyTakeaways: [
        "Voice-native GenAI companion for conversational financial queries",
        "Reliable intent classification for personal finance and spending habits",
        "Mobile-first companion reducing friction to access financial health data",
      ],
      myRole: "Product Manager",
      roleBullets: [
        "Led discovery phase and mapped user intent taxonomy for finance",
        "Designed the voice-first multimodal interaction model",
        "Managed prompt engineering for plain-language financial explanations",
        "Conducted initial prototype and feasibility testing with Whisper/LLM engines",
      ],
      futureImprovements: "Integrate multi-modal chat so users can share charts along with voice.",
      evaluation: {
        datasetSize: "TBD",
        method: "Ground truth comparison and manual validation.",
        primaryMetric: "Intent classification accuracy and response relevance.",
        status: "Evaluation currently in progress. Metrics will be added after testing.",
      },
    },
    {
      id: "memora",
      title: "Memora",
      status: "Live",
      category: "Shipped Product",
      shortProblem: "Users take thousands of screenshots that become unsearchable clutter.",
      shortSolution: "An automated extraction tool that indexes screenshots with semantic search.",
      outcome: "Transforms an unstructured screenshot archive into a semantic knowledge base you can query.",
      githubUrl: "https://github.com/Ruthwik-Data",
      liveUrl: "https://memora-opal.vercel.app/",
      image: "/memora.webp",
      galleryUrls: ["/memora.webp"],
      overview: [
        "Transformed a static image folder into a searchable knowledge base.",
        "Implemented semantic search using embedding-based retrieval.",
      ],
      problem: "Screenshots contain valuable knowledge but are completely opaque to traditional text search.",
      whyThisMatters: "Screen-capture is the default 'save' action for modern research. Memora unlocks that trapped knowledge by making it instantly searchable by meaning, not just filenames.",
      usersAndJobs: "Knowledge workers and researchers who save visual references.",
      solution: "An automated extraction tool that indexes screenshots using vision models and vector search.",
      architectureContent: "Screenshot → OCR / VLM → Embedding Model → Vector DB → Semantic Search",
      techStack: ["Python", "Vector Databases", "Vision Models", "FastAPI"],
      resultsAndMetrics: "Improved retrieval relevance through embedding-based semantic search.",
      keyTakeaways: [
        "Transforms unsearchable screenshot archives into indexed knowledge bases",
        "Semantic search implementation for visual reference retrieval",
        "Highly relevant retrieval through embedding-based semantic architectures",
      ],
      myRole: "Product Manager",
      roleBullets: [
        "Designed the vision-to-vector system architecture",
        "Evaluated embedding models for performance vs. cost trade-offs",
        "Led UX discovery for visual memory search patterns",
        "Mapped semantic search requirements for researcher and designer workflows",
      ],
      futureImprovements: "Automatic clustering of screenshots by topic without user input.",
      evaluation: {
        datasetSize: "TBD",
        method: "Ground truth comparison and manual validation.",
        primaryMetric: "Retrieval precision and recall on a labeled screenshot dataset.",
        status: "Evaluation currently in progress. Metrics will be added after testing.",
      },
    },
    {
      id: "warmlist",
      title: "Warmlist",
      status: "Live",
      category: "Shipped Product",
      shortProblem: "Tracking high-intent network leads usually falls back to messy spreadsheets.",
      shortSolution: "A smart CRM that uses AI to score and remind you about warm interactions.",
      outcome: "Replaces manual lead tracking with an AI-prioritized relationship queue.",
      githubUrl: "https://github.com/Ruthwik-Data",
      liveUrl: "https://warmlist-dun.vercel.app/",
      image: "/warmlist_viz.png",
      galleryUrls: ["/warmlist_viz.png", "/warmlist.webp"],
      overview: [
        "Created a zero-friction CRM for relationship management.",
        "Replaced manual triage with LLM-based lead prioritization.",
      ],
      problem: "Founders lose track of 'warm' conversations across LinkedIn, email, and Twitter.",
      whyThisMatters: "Founders and PMs lose thousands in deal value by failing to follow up with 'warm' leads. Prioritizing these contacts is critical for growth and network retention.",
      usersAndJobs: "Founders and PMs managing high-intent leads and fundraising contacts.",
      solution: "A smart CRM that ingests communication history, uses AI to score relationship temperature, and sets follow-ups.",
      architectureContent: "Email/LinkedIn Data → LLM Scoring → Priority Queue → Dashboard",
      techStack: ["Next.js", "Tailwind", "LLM APIs"],
      resultsAndMetrics: "Warmlist is currently in evaluation. The product works in the UI, but the latest automated evaluation path did not complete real summary generation, so final performance metrics are not yet portfolio-ready.",
      keyTakeaways: [
        "Replaces messy spreadsheets with an AI-prioritized relationship queue",
        "Automated lead temperature scoring and relationship follow-ups",
        "Evaluation-driven design with 20 lead transcript segments for initial testing",
      ],
      myRole: "Product Manager",
      roleBullets: [
        "Defined lead scoring rubrics to quantify 'relationship temperature'",
        "Designed user flow for priority-first relationship management",
        "Created evaluation path for lead prioritization quality",
        "Iterated on CRM dashboard layout to minimize user friction",
      ],
      futureImprovements: "Direct integrations with Gmail and LinkedIn for automatic syncing.",
      evaluation: {
        datasetSize: "20 transcript segments",
        method: "Automated evaluation run plus manual product verification.",
        primaryMetric: "Lead prioritization quality and summary usefulness.",
        status: "Evaluation path under debugging. Final metrics will be added after rerunning the test through the working API path.",
      },
    },
    {
      id: "sugarshield",
      title: "SugarShield",
      status: "Live",
      category: "System Design",
      shortProblem: "Health-conscious shoppers struggle to judge sugar quality from ingredient lists quickly.",
      shortSolution: "Rule-based ingredient classifier that detects hidden sugars and artificial sweeteners.",
      outcome: "Improved recall from 0.31 to 0.77 while maintaining 1.00 precision on 15 food products.",
      metric: "0.77 Recall · 1.00 Precision · 0 False Positives",
      githubUrl: "https://github.com/Ruthwik-Data/sugarshield",
      liveUrl: "https://sugarshield.vercel.app/",
      image: "/sugarshield_viz.png",
      galleryUrls: ["/sugarshield_viz.png", "/sugarshield.webp", "/sugarshield_diagram.png"],
      overview: [
        "Evaluated on 15 labeled food products",
        "Improved recall from 0.31 to 0.77 after expanding the sweetener dictionary",
        "Maintained 1.00 precision with 0.00 false positives",
      ],
      problem: "Health-conscious shoppers struggle to judge sugar quality from ingredient lists quickly, especially when labels are dense or inconsistent.",
      whyThisMatters: "Nutrition labels are notoriously hard to parse at a glance; shoppers need instantaneous safety signals when judging nutritional trade-offs.",
      usersAndJobs: "Shoppers who want a fast buy/skip signal while reading packaged food labels.",
      solution: "A rule-based ingredient classifier that detects hidden sugars, artificial sweeteners, and sugar alcohols from ingredient text and returns an explainable decision.",
      architectureContent: "Label Text → Detection Dictionary → Sugar Category Matching → Rules Engine → PASS / WARN Decision",
      techStack: ["Next.js", "Tailwind", "TypeScript", "Rules Engine"],
      resultsAndMetrics: "Dataset size: 15 labeled products. Achieved 0.77 recall (improved from 0.31) and 1.00 precision with 0.00 false positives (FNR: 0.23). The system provides clear Buy/Skip signals based on an expandable rules engine.",
      keyTakeaways: [
        "Rule-based ingredient classifier with zero false positives",
        "Automated hidden sugar detection across complex nutrition labels",
        "Improved recall from 0.31 to 0.77 using an expanded sweetener dictionary",
      ],
      myRole: "Product Manager",
      roleBullets: [
        "Built ground-truth evaluation datasets for labeled food products",
        "Expanded technical sweetener dictionary to capture emerging artificial ingredients",
        "Developed explanation layer for decision transparency",
        "Led experimentation and refinement of rule-based logic to maintain 1.00 precision",
      ],
      futureImprovements: "Handle incomplete ingredient lists more gracefully and expand to OCR-based label capture from camera input.",
      evaluation: {
        datasetSize: "15 labeled food products",
        method: "Ground truth comparison against labeled ingredient classifications.",
        primaryMetric: "Recall, precision, and false positive rate.",
        status: "Validated and ready to show in portfolio.",
      },
    },
    {
      id: "sleepsense",
      title: "SleepSense",
      status: "Prototype",
      category: "Product Thinking",
      hideFromGrid: true,
      shortProblem: "People take fragmented notes when half-awake that don't translate into action.",
      shortSolution: "Intelligent parsing system that structures morning-after notes into sleep hygiene trends.",
      outcome: "Transforms unstructured sleep journal text into structured insights about sleep hygiene.",
      image: "/scorecard_eval_loop.png",
      galleryUrls: ["/scorecard_eval_loop.png"],
      overview: [
        "Prototyped a parsing tool for messy text logs.",
        "Focused on extracting structured habits from unstructured, emotional writing.",
      ],
      problem: "People log sleep habits in fragmented, sleepy syntax. This doesn't translate into actionable graphs.",
      whyThisMatters: "Personal tracking fails when the friction of data entry is too high. SleepSense allows users to jot down informal notes and still get clean, structured data.",
      usersAndJobs: "Bio-hackers and individuals trying to improve sleep through habit tracking.",
      solution: "An intelligent parsing API that translates messy text into structured JSON mapping habits against sleep quality scores.",
      architectureContent: "Raw Text Notes → LLM Parsing → JSON Structuring → Daily Insights",
      techStack: ["Python", "FastAPI", "LLMs"],
      resultsAndMetrics: "The prototype parses unstructured sleep notes into structured insight payloads.",
      keyTakeaways: [
        "Automated parsing of unstructured, informal sleep journal notes",
        "Systemic conversion of messy habits into structured JSON trends",
        "Discovery-focused prototype exploring LLM-based behavior extraction",
      ],
      myRole: "Product Manager",
      roleBullets: [
        "Ideated the core behavior-extraction concept",
        "Developed prompt architecture for messy text-parsing",
        "Mapped unstructured habits to structured health trends",
        "Evaluated parsing accuracy on annotated sleep entries",
      ],
      futureImprovements: "Integrate with Apple Health to correlate subjective notes with objective sensor data.",
      evaluation: {
        datasetSize: "TBD",
        method: "Ground truth comparison and manual validation.",
        primaryMetric: "Parsing accuracy on annotated sleep journal entries.",
        status: "Evaluation currently in progress. Metrics will be added after testing.",
      },
    },
  ],
  aiLabs: [
    {
      name: "SleepSense",
      description: "AI-powered system transforming messy sleep notes into structured insights and patterns.",
      takeaway: "Experiment exploring how LLMs can convert unstructured personal health notes into structured behavioral insights.",
      tags: ["AI", "Prototype", "Experiment"],
      url: "/projects/sleepsense",
    },
    {
      name: "Rellos Experiment Hub",
      description: "A collection of AI experiments, product explorations, and learnings from tools and workflows I test. This hub acts as a personal lab notebook where I document experiments, notes, and insights from AI products I explore.",
      takeaway: "A living record of how I explore, evaluate, and learn from emerging AI tools and product patterns.",
      tags: ["Experiment Hub"],
      url: "https://rellos-experiment-hub.lovable.app",
      ctaLabel: "Explore Experiments",
    },
    {
      name: "Agentic Email Sorter",
      description: "An autonomous agent that triages incoming emails based on custom priority rules.",
      takeaway: "Demonstrates how I design agentic workflows with evaluation hooks and safety guardrails.",
      tags: ["Agents", "Automation", "Eval"],
      url: "https://lovable.example/agentic-email",
    },
    {
      name: "RAG Financial Analyst",
      description: "Retrieval-Augmented Generation over 10-K filings to auto-answer investor queries.",
      takeaway: "Showcases my approach to building cost-effective RAG systems tailored for complex documents.",
      tags: ["RAG", "Data", "LLMs"],
      url: "https://lovable.example/rag-finance",
    },
  ],
};

// Blog (/writing)
export const blogPageContent: BlogPageContent = {
  seo: {
    title: "Writing | Ruthwik Arepelly",
    description: "Articles on Product Management, AI, and Socio-Technological trends.",
    image: identity.logo,
  },
  subtitle: "Product Stories & Insights",
};

export const skillCategories = [
  {
    title: "AI Product",
    skills: ["LLM Evals & Guardrails", "RAG / Agent Systems", "GPT-4o Vision", "Semantic Search", "Prompt Engineering"],
  },
  {
    title: "Product Strategy",
    skills: ["B2B SaaS Strategy", "PMF Discovery", "Unit Economics", "Experimentation", "User Research"],
  },
  {
    title: "Technical",
    skills: ["TypeScript", "Python", "SQL", "Next.js", "Astro", "Vercel / GitHub Actions"],
  },
];
